export type JobStatus = "Applied" | "Not Applied" | "Interview" | "Rejected" | "Saved";

export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  role: string;
  status: JobStatus;
  dateAdded: string;
  link: string;
  isBookmarked: boolean;
}

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechFlow",
    location: "San Francisco, CA",
    role: "Frontend Developer",
    status: "Applied",
    dateAdded: "2026-04-01",
    link: "https://example.com/apply/1",
    isBookmarked: true,
  },
  {
    id: "2",
    title: "Data Analyst",
    company: "DataViz Corp",
    location: "New York, NY",
    role: "Data Analyst",
    status: "Interview",
    dateAdded: "2026-04-02",
    link: "https://example.com/apply/2",
    isBookmarked: false,
  },
  {
    id: "3",
    title: "Backend Engineer (Go)",
    company: "Streamline Systems",
    location: "Remote",
    role: "Backend Developer",
    status: "Not Applied",
    dateAdded: "2026-04-03",
    link: "https://example.com/apply/3",
    isBookmarked: false,
  },
  {
    id: "4",
    title: "Full Stack Developer",
    company: "Nimbus Solutions",
    location: "Austin, TX",
    role: "Full Stack",
    status: "Rejected",
    dateAdded: "2026-03-28",
    link: "https://example.com/apply/4",
    isBookmarked: true,
  },
  {
    id: "5",
    title: "Junior Frontend Dev",
    company: "StartUp Inc",
    location: "San Francisco, CA",
    role: "Frontend Developer",
    status: "Applied",
    dateAdded: "2026-04-05",
    link: "https://example.com/apply/5",
    isBookmarked: false,
  },
  {
    id: "6",
    title: "Data Scientist",
    company: "Insight AI",
    location: "Remote",
    role: "Data Analyst",
    status: "Not Applied",
    dateAdded: "2026-04-06",
    link: "https://example.com/apply/6",
    isBookmarked: false,
  },
  {
    id: "7",
    title: "Senior Backend (Python)",
    company: "PyLogic",
    location: "Berlin, DE",
    role: "Backend Developer",
    status: "Interview",
    dateAdded: "2026-04-07",
    link: "https://example.com/apply/7",
    isBookmarked: false,
  },
  {
    id: "8",
    title: "Software Engineer",
    company: "OmniTech",
    location: "London, UK",
    role: "Full Stack",
    status: "Applied",
    dateAdded: "2026-04-08",
    link: "https://example.com/apply/8",
    isBookmarked: true,
  },
  {
    id: "9",
    title: "React Developer",
    company: "Pixel Perfect",
    location: "San Francisco, CA",
    role: "Frontend Developer",
    status: "Not Applied",
    dateAdded: "2026-04-09",
    link: "https://example.com/apply/9",
    isBookmarked: false,
  },
  {
    id: "10",
    title: "Systems Architect",
    company: "Core Infrastructure",
    location: "Seattle, WA",
    role: "Backend Developer",
    status: "Applied",
    dateAdded: "2026-04-10",
    link: "https://example.com/apply/10",
    isBookmarked: false,
  },
  {
    id: "11",
    title: "Product Analyst",
    company: "Growth Labs",
    location: "Remote",
    role: "Data Analyst",
    status: "Applied",
    dateAdded: "2026-04-11",
    link: "https://example.com/apply/11",
    isBookmarked: false,
  },
  {
    id: "12",
    title: "Senior Full Stack Dev",
    company: "Enterprise Co",
    location: "Chicago, IL",
    role: "Full Stack",
    status: "Rejected",
    dateAdded: "2026-03-15",
    link: "https://example.com/apply/12",
    isBookmarked: false,
  },
  {
    id: "13",
    title: "Lead Frontend Engineer",
    company: "Design Systems",
    location: "San Jose, CA",
    role: "Frontend Developer",
    status: "Interview",
    dateAdded: "2026-04-10",
    link: "https://example.com/apply/13",
    isBookmarked: false,
  },
  {
    id: "14",
    title: "ML Engineer",
    company: "Future AI",
    location: "Silicon Valley, CA",
    role: "Data Analyst",
    status: "Not Applied",
    dateAdded: "2026-04-11",
    link: "https://example.com/apply/14",
    isBookmarked: true,
  },
  {
    id: "15",
    title: "Network Programmer",
    company: "FastConnect",
    location: "Montreal, CA",
    role: "Backend Developer",
    status: "Applied",
    dateAdded: "2026-04-11",
    link: "https://example.com/apply/15",
    isBookmarked: false,
  },
];
